import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// this seems to be something recent with Next.js. This is using the Metadata API
// https://nextjs.org/docs/app/building-your-application/optimizing/metadata
// you can use generateMetaData to grab dynamically changed metadata.
// API reference below of all the metadata fields you can use with generateMetaData function
// https://nextjs.org/docs/app/api-reference/functions/generate-metadata

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>Hello World!!!</div>
        {children}
      </body>
    </html>
  );
}
